name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        features: [default, serde]
        os: [ubuntu-latest, macos-latest, windows-latest]
        crate: ["rust-dependency1", "rust-dev"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install components
        run: rustup component add clippy rustfmt

      - name: Build & Test ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: |
          cargo build --verbose --features "${{ matrix.features }}"
          cargo test  --verbose --features "${{ matrix.features }}"

      - name: Check formatting ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo fmt -- --check

      - name: Lint with Clippy ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo clippy --all-targets --all-features -- -D warnings
